name = "worker"
main = "build/index.js"
compatibility_date = "2026-03-24"

[build]
command = "cargo install --locked \"worker-build@^0.7\" && worker-build --profile wasm"

[vars]
ISSUER = "https://auth.laggy.computer"

[[kv_namespaces]]
binding = "AUTH_SESSIONS"
id = "6c17844d11854154987d7220db10f3a7"

[[kv_namespaces]]
binding = "AUTH_KEYS"
id = "9662f50f89bb4c8c8b0619abe797b7ef"
