// @generated automatically by Diesel CLI.

diesel::table! {
    /// Representation of the `refresh_token` table.
    ///
    /// (Automatically generated by Diesel.)
    refresh_token (id) {
        /// The `id` column of the `refresh_token` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `user_id` column of the `refresh_token` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Varchar,
        /// The `email` column of the `refresh_token` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        email -> Varchar,
        /// The `name` column of the `refresh_token` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Varchar,
        /// The `picture` column of the `refresh_token` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        picture -> Nullable<Varchar>,
        /// The `client_id` column of the `refresh_token` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        client_id -> Varchar,
        /// The `scope` column of the `refresh_token` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        scope -> Varchar,
        /// The `google_refresh_token` column of the `refresh_token` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        google_refresh_token -> Nullable<Varchar>,
        /// The `expires` column of the `refresh_token` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        expires -> Timestamptz,
    }
}
