// @generated automatically by Diesel CLI.

diesel::table! {
    /// Representation of the `jwk` table.
    ///
    /// (Automatically generated by Diesel.)
    jwk (id) {
        /// The `id` column of the `jwk` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Varchar,
        /// The `key_data` column of the `jwk` table.
        ///
        /// Its SQL type is `Jsonb`.
        ///
        /// (Automatically generated by Diesel.)
        key_data -> Jsonb,
    }
}
